services:
  backend:
    build: ./backend
    container_name: bice-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/chroma_db:/app/chroma_db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: bice-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

